<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KIjqkQ.' shared service.

return $this->privates['.service_locator.KIjqkQ.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'product' => ['privates', '.errored..service_locator.KIjqkQ..App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.KIjqkQ.": it references class "App\\Entity\\Product" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
]);
