Query:
  type: object
  config:
    fields:
      Article:
        type: 'Article'
        args:
          id:
            description: 'Resolves Article using its id.'
            type: 'Int!'
        resolve: "@=resolver('Article', [args['id']])"
      Articles:
        type: '[Article]'
        resolve: "@=resolver('Articles')"
      Author:
        type: 'Author'
        args:
          id:
            description: 'Resolves Author using its id.'
            type: 'Int!'
        resolve: "@=resolver('Author', [args['id']])"
      Authors:
        type: '[Author]'
        resolve: "@=resolver('Authors')"
      Category:
        type: 'Category'
        args:
          id:
            description: 'Resolves Category using its id.'
            type: 'Int!'
        resolve: "@=resolver('Category', [args['id']])"
      Categories:
        type: '[Category]'
        resolve: "@=resolver('Categories')"
      Comment:
        type: 'Comment'
        args:
          id:
            description: 'Resolves Comment using its id.'
            type: 'Int!'
        resolve: "@=resolver('Comment', [args['id']])"
      Comments:
        type: '[Comment]'
        resolve: "@=resolver('Comments')"