<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Resolver\CategoryResolver' shared autowired service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Resolver/AliasedInterface.php';
include_once $this->targetDirs[3].'/src/Resolver/CategoryResolver.php';

return $this->services['App\Resolver\CategoryResolver'] = new \App\Resolver\CategoryResolver(($this->privates['App\Repository\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php')));
