<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.type_resolver' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Resolver/FluentResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Resolver/AbstractResolver.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Resolver/TypeResolver.php';

$this->services['overblog_graphql.type_resolver'] = $instance = new \Overblog\GraphQLBundle\Resolver\TypeResolver();

$instance->addSolution('overblog_graphql.definition.string_type', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'overblog_graphql.definition.string_type']], [0 => 'String'], ['id' => 'overblog_graphql.definition.string_type', 'aliases' => [0 => 'String'], 'alias' => 'String']);
$instance->addSolution('overblog_graphql.definition.int_type', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'overblog_graphql.definition.int_type']], [0 => 'Int'], ['id' => 'overblog_graphql.definition.int_type', 'aliases' => [0 => 'Int'], 'alias' => 'Int']);
$instance->addSolution('overblog_graphql.definition.float_type', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'overblog_graphql.definition.float_type']], [0 => 'Float'], ['id' => 'overblog_graphql.definition.float_type', 'aliases' => [0 => 'Float'], 'alias' => 'Float']);
$instance->addSolution('overblog_graphql.definition.boolean_type', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'overblog_graphql.definition.boolean_type']], [0 => 'Boolean'], ['id' => 'overblog_graphql.definition.boolean_type', 'aliases' => [0 => 'Boolean'], 'alias' => 'Boolean']);
$instance->addSolution('overblog_graphql.definition.id_type', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'overblog_graphql.definition.id_type']], [0 => 'ID'], ['id' => 'overblog_graphql.definition.id_type', 'aliases' => [0 => 'ID'], 'alias' => 'ID']);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\AuthorInputType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\AuthorInputType']], [0 => 'AuthorInput'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\AuthorInputType', 'aliases' => [0 => 'AuthorInput'], 'alias' => 'AuthorInput', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\ArticleInputType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\ArticleInputType']], [0 => 'ArticleInput'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\ArticleInputType', 'aliases' => [0 => 'ArticleInput'], 'alias' => 'ArticleInput', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\CommentType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CommentType']], [0 => 'Comment'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CommentType', 'aliases' => [0 => 'Comment'], 'alias' => 'Comment', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\CategoryInputType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CategoryInputType']], [0 => 'CategoryInput'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CategoryInputType', 'aliases' => [0 => 'CategoryInput'], 'alias' => 'CategoryInput', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\QueryType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\QueryType']], [0 => 'Query'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\QueryType', 'aliases' => [0 => 'Query'], 'alias' => 'Query', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\ArticleType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\ArticleType']], [0 => 'Article'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\ArticleType', 'aliases' => [0 => 'Article'], 'alias' => 'Article', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\CommentInputType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CommentInputType']], [0 => 'CommentInput'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CommentInputType', 'aliases' => [0 => 'CommentInput'], 'alias' => 'CommentInput', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\CategoryType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CategoryType']], [0 => 'Category'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\CategoryType', 'aliases' => [0 => 'Category'], 'alias' => 'Category', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\AuthorType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\AuthorType']], [0 => 'Author'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\AuthorType', 'aliases' => [0 => 'Author'], 'alias' => 'Author', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\MutationSuccessType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\MutationSuccessType']], [0 => 'MutationSuccess'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\MutationSuccessType', 'aliases' => [0 => 'MutationSuccess'], 'alias' => 'MutationSuccess', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\MutationType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\MutationType']], [0 => 'Mutation'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\MutationType', 'aliases' => [0 => 'Mutation'], 'alias' => 'Mutation', 'generated' => true]);
$instance->addSolution('Overblog\\GraphQLBundle\\__DEFINITIONS__\\PageInfoType', [0 => [0 => $this, 1 => 'get'], 1 => [0 => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\PageInfoType']], [0 => 'PageInfo'], ['id' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__\\PageInfoType', 'aliases' => [0 => 'PageInfo'], 'alias' => 'PageInfo', 'generated' => true]);

return $instance;
