<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVrx4T2E\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVrx4T2E/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVrx4T2E.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVrx4T2E\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVrx4T2E\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Vrx4T2E',
    'container.build_id' => '30df61ea',
    'container.build_time' => 1553901191,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVrx4T2E');
