<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvov6GH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvov6GH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHvov6GH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHvov6GH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHvov6GH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hvov6GH',
    'container.build_id' => '9fb5027b',
    'container.build_time' => 1553010553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvov6GH');
